### ISSUE TITLE
KeyClu crashes on editing "My Shortcuts" + Unable to Remove Shortcuts

### ISSUE THREAD

**Issue by natejohnathan** [Anze/KeyCluCask#36]
Newest version from 2 weeks ago. 00.15 I think. I am able to select a category (i.e., Global or a specific application) without trouble. Adding a shortcut in "My Shortcuts" appears to not be an issue, although I'm not sure what the purpose of the section is, as it doesn't seem to do anything, at least the way I tried to use it. However, when trying to remove a shortcut (from the visible list), there doesn't appear to be a way to do this. Also, when I try to change the hotkey, it appears to allow that, but then the app crashes and quits when confirming. It does appear to hold the changed value, however.

Also, I can't successfully find a way to remove a shortcut while still leaving the item on the list. In many apps, there is an ✗ you can click, or you can highlight the shortcut as if changing it and then click backspace. I can't find any way here.

Note, please do not implement the backspace method if it would conflict with setting a hotkey using backspace. If both are possible, no problem.

**Comment by Anze** [comment]
Hey [natejohnathan](https://github.com/natejohnathan)
Thanks for bringing these issues to my attention.

Firstly, I'm aware of the problem that causes a crash when adding a new shortcut due to simultaneous editing of two values. This issue has already been resolved and will be included in the next release.

Regarding the deletion of custom shortcuts from the list, when you select a row in the table, a delete button (represented by a minus icon) appears at the bottom right corner of the table. I've taken steps to make it more user-friendly, by making it more visible and accessible.

As for the option to reset a shortcut to be empty, this is not currently in plans. However, you can easily remove an unwanted item from the list if it's no longer needed.

If you have any further questions or concerns, please don't hesitate to ask.

**Comment by Anze** [comment]
Absolutely, both of the features you mentioned will be implemented.
