### ISSUE TITLE
[feature] KeyClu & skhd

### ISSUE THREAD

**Issue by Anze** [Anze/KeyCluCask#55]
Can I list my own shortcuts I have inside my skhdrc?

Basically I would like to press a keybind and have it show all my shortcuts I have listed in my skhd. Is this possible, even if I have to manually add them.

I guess what I'm asking for is the ability to add custom sheets and assign to a key binding in skhd
hyper - s : KeyClu --sheet SHEETNAME --toggle-persistent 

This would be a great feature for programs like Yabai/skhd and other global shortcuts not related to s specific program!

Of course if something similar doesn't already exist.

Thanks!

_Originally posted by @gldtn in https://github.com/Anze/KeyCluCask/discussions/46_

**Comment by johnMocingbird** [comment]
I saw that this was marked as complete, but I do not understand how I can create my own custom sheet. The only sheets that work for me, via the cli, are the ones included in the wiki

**Comment by johnMocingbird** [comment]
I just check where this issue was created from. And the feature is pretty different than what I was thinking of for my use case.

What issue do I want to solve? I want a cheat sheet for each individual SKHD mode.

How? Well, it's very easy to run a script when changing modes in skhd... If I could simply have the ability to create "custom sheets" add the keybindings for each mode inside of keyclu, I would be one happy dude..  I wouldn't mind if I had to manually create each keybinding. I don't need it to parse it out of the skhdrc. See the snippets below.

```sh
#skhdrc
:: window_management : ~/scripts/sketchy_helpers.sh window_mode
```

```sh
#sketchy_helpers.sh

function window_mode() {
	sketchybar -m --set skhd_mode icon.color="0xFF83A1F1"
	sketchybar -m --set skhd_mode icon="[W]"
        /Applications/KeyClu.app/Contents/MacOS/KeyClu --toggle-panel --sheet window_mode
}

function default_mode() {
	sketchybar -m --set skhd_mode icon.color="0xFF83A1F1"
	sketchybar -m --set skhd_mode icon="[D]"
        /Applications/KeyClu.app/Contents/MacOS/KeyClu --toggle-panel 
}

```

It would be amazing if we could have it toggle the "persistent mode" instead of the other one. I can very easily have skhd toggle it off with a keybinding OR once back to default mode.
