### ISSUE TITLE
Alternative Rainbow Mode Option

### ISSUE THREAD

**Issue by wanwindwalker** [Anze/KeyCluCask#76]
### Proposal

Second Rainbow Mode where modifier keys are not colored based on the amount of hotkeys used in the shortcut but color based on their type. Control, Command, Option and Shift each have their own identifying color in all shortcuts and letters (and symbols and non-modifiers) stay White everywhere.

Color scheme could be:
Command - Blue
Shift - Green
Option - Yellow
Control - Orange
fn - Red

I based it on how frequently each modifier is used.

Here is a colorblindness color scheme that you can add as an aditional option:
Command - #006ddb
Shift - #22cf22
Option - #ffdf4d
Control - #db6d00
fn - #920000

**Comment by wanwindwalker** [comment]
And I guess for Hyperkey users make Caps Lock pink

**Comment by Anze** [comment]
Hey [wanwindwalker](https://github.com/wanwindwalker),
I believe for the alternative, it would be best to let you decide (customize) which colors you want to see. Anyway, it was planned to be customizable later.

> And I guess for Hyperkey users make Caps Lock pink
Technically, Caps Lock isn't recognized as a valid modifier or key. However, it can be assigned to hotkeys in some apps. The question arises whether it should be displayed as a modifier since it does function as one. Or, when assigned as a hotkey, it effectively becomes a non-modifier. Currently, there are no plans to display Caps Lock as a valid modifier or key, but it's a possibility for the future.

**Comment by wanwindwalker** [comment]
I'm not user of Hyperkey I didn't know it didn't function the same way. Yeah customizable is always preferable sorry if I suggest a feature that was already planned I didn't realzie it was.

**Comment by Anze** [comment]
Don't worry if the feature is already in plans — I appreciate all suggestions. It shows that I'm thinking in the right direction.

**Comment by Anze** [comment]
Hey [wanwindwalker](https://github.com/wanwindwalker),
I've just released a new version. You can now customize these colors.
